name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up uv with Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv pip install -e ".[dev,cli]"

    - name: Lint with ruff
      run: |
        uv run ruff check --output-format=github .

    - name: Type check with mypy
      run: |
        uv run mypy safie_mediafile

    - name: Test with pytest
      run: |
        uv run pytest --cov=safie_mediafile tests/ 
